### PR TITLE
query implementation?

### PR DESCRIPTION
**Pull request by garryyao**
I intend to use this pkg standalone as replacement of the original `troopjsd-data` module but obviously the request && batch implementation, aka. the original `troopjs-data/query/service` was missing here, considering that as one piece of the most important Troop query implementation, would it be possible to ship it in this pkg as well?

### CODE REVIEW

**Comment by garryyao** [comment]
I have ported the original query service impl. to the above proposed API above, review?

**Comment by mikaelkaron** [comment]
Taking a look at it now. I'm a bit choked at the moment but comments will follow shortly.

**Comment by garryyao** [comment]
Thanks Mike I understand time is really precious for you, unlike us.

**Comment by garryyao** [comment]
I am glad to show you a live example of how this new `mu-data` idea makes the general consumption of Troop query much easier, before v.s. after:
https://github.com/garryyao/localhandler/commit/09a96598155076618f8807db5cdc1e81f308e8ae

**Comment by mikaelkaron** [comment]
That does indeed look quite nice.

I did have a twist on the idea but after looking at this I feel I have to think about it (I sort of like the self contained nature of this, was thinking of something using an emitter but maybe not).

**Comment by garryyao** [comment]
@mikaelkaron what's your emitter idea could you elaborate a bit? I can imagine only with a higher level of abstraction, e.g. when you want to provide this as a query service in troop, the emitter could fit in. But I would rather keep the building block alike package like mu-data as lean.

Actually there's one missing feature I can imagine, user may sometimes need post-process each indexed object in cache (client-side computation), which seems to be impossible now, but that desires a different ticket.

**Comment by garryyao** [comment]
If you guys could verify the tests are ok, I think we could merge.

**Pull request closed without merging**
